services:
  nest:
    container_name: nest
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    links:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: nest
    volumes:
      - data-volume:/data/db

  frontend:
    build:
      context: ./frontend
    command: yarn dev
    volumes:
      - ./frontend/package.json:/home/node/package.json
      - ./frontend/src:/home/node/src:cached
    ports:
      - 5173:5173
    env_file:
      - ./frontend/.env

volumes:
  data-volume:
